# Basic Information 
title: Your Name
position: Your Position
affiliation: Your Institution
affiliation_link: https://your-institution-website.com/
affiliation_logo: ./assets/img/your-logo.svg
email: your.email (at) domain.com

# Search Engine Optimization (SEO)
keywords: your name, keywords, research interests
canonical: https://your-username.github.io
description: Your brief description about yourself and your research interests.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=YOUR_ID
github_link: https://github.com/your-username/
linkedin: https://www.linkedin.com/in/your-profile/
twitter: https://twitter.com/your-handle/

# Images 
avatar: ./assets/img/your-avatar.jpg

# Footnotes
footnote: Powered by minimal-light
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Remove the following line if you don't want to use ClustrMaps
# clustrmaps_id: YOUR_ID

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
