site_name: Guanxuan JIANG
site_url: https://jgxuann.github.io/
nav:
    - Home: index.md
    #- Demo: demo.md

# Change themes：
# （1） conda install -c conda-forge mkdocs-bootswatch
# （2） https://mkdocs.github.io/mkdocs-bootswatch/#flatly This link contents all available themes
theme:
    name: flatly
