site_name: Guanxuan JIANG
site_url: https://jgxuann.github.io/
nav:
  - Home: index.md
  - Selected Projects: selected_projects.md
  - Blog: blog.md

theme:
  name: flatly

plugins:
- search
- git-revision-date
